"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "./auth-provider";
import { CurrencyDrawerRow, CurrencyDropdown, CurrencySheet } from "./currency-menu";
import { Price } from "./currency-provider";

const drawerLevels: Record<string, string[]> = { root: ["Shop All", "PC Parts", "Computers", "Gaming", "Monitors", "Peripherals", "Storage", "Networking", "Digital Games", "Software", "PC Builder", "Brands", "Deals", "Clearance"], "PC Parts": ["Graphics Cards", "Processors", "Motherboards", "Memory", "Storage", "Power Supplies", "PC Cases", "Cooling", "Fans", "Accessories"], "Digital Games": ["PC Games", "Steam", "Xbox", "PlayStation", "Nintendo", "DLC", "Preorders", "New Releases", "Best Sellers", "On Sale", "Under $10", "Genres", "Publishers"] };

export default function SiteHeader() {
  const { user } = useAuth();
  const [drawer, setDrawer] = useState(false); const [level, setLevel] = useState("root"); const drawerRef = useRef<HTMLElement | null>(null);
  const [sheet, setSheet] = useState(false);
  const closeDrawer = useCallback(() => { setDrawer(false); setLevel("root"); setSheet(false); }, []);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key !== "Escape") return; if (sheet) setSheet(false); else closeDrawer(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [closeDrawer, sheet]);
  useEffect(() => { document.body.style.overflow = drawer ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [drawer]);
  useEffect(() => { if (drawer) drawerRef.current?.querySelector<HTMLButtonElement>("button")?.focus(); }, [drawer, level]);
  const trapFocus = (event: React.KeyboardEvent<HTMLElement>) => { if (event.key !== "Tab") return; const items = Array.from(drawerRef.current?.querySelectorAll<HTMLElement>("button, a, input") ?? []).filter((el) => !el.closest("[inert]")); if (!items.length) return; const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  const firstName = user?.name?.split(" ")[0];
  const accountHref = user ? "/account" : "/login";
  return <><header><div className="topbar"><span>Free shipping on orders over <Price thb={120000} /></span><span>Help & support</span></div><div className="header-main"><button className="mobile-menu" aria-label="Open products menu" onClick={() => setDrawer(true)}>☰</button><Link className="logo" href="/">core<span>cart</span></Link><label className="search"><span>⌕</span><input aria-label="Search products" placeholder="Search PC parts, games, laptops, software..." /></label><button className="utility location"><b>⌖</b><span>Deliver to<br/><strong>Bangkok, Thailand</strong></span></button><CurrencyDropdown /><Link className="utility desktop-utility" href={accountHref}><b>♙</b><span>{firstName ? `Hello, ${firstName}` : "Hello, sign in"}<br/><strong>Account</strong></span></Link><Link className="utility desktop-utility" href={user ? "/account/orders" : "/login"}><b>□</b><span>Returns<br/><strong>& Orders</strong></span></Link><Link className="mobile-account" href={accountHref} aria-label={user ? "Your account" : "Sign in"}>♙</Link><button className="cart" aria-label="Shopping cart"><b>🛒</b><span>Cart</span><i>2</i></button></div><div className="mobile-location">⌖ Deliver to <strong>Bangkok, Thailand</strong></div><nav><button onClick={() => setDrawer(true)}>☰ <strong>Products</strong></button>{["PC Parts", "Computers", "Gaming", "Digital Games", "Deals", "PC Builder", "Brands", "Clearance"].map(x => <a href="#" key={x}>{x}</a>)}</nav></header>
  {drawer && <div className="drawer-wrap" role="presentation"><button className="backdrop" aria-label="Close products menu" onClick={closeDrawer}/><aside ref={drawerRef} onKeyDown={trapFocus} className="drawer" aria-label="Product categories" role="dialog" aria-modal="true"><div className="drawer-main" inert={sheet}><div className="drawer-top">{level !== "root" ? <button onClick={() => setLevel("root")}>← {level}</button> : <strong>Products</strong>}<button onClick={closeDrawer} aria-label="Close menu">×</button></div><ul>{drawerLevels[level].map(item => <li key={item}><button onClick={() => drawerLevels[item] ? setLevel(item) : closeDrawer()}>{item}{drawerLevels[item] && <span>›</span>}</button></li>)}</ul><CurrencyDrawerRow onOpen={() => setSheet(true)} /><div className="drawer-help">{user ? <><Link href="/account" onClick={closeDrawer}>Your account</Link> · <Link href="/account/orders" onClick={closeDrawer}>Orders</Link></> : <><Link href="/login" onClick={closeDrawer}>Sign in</Link> · <Link href="/register" onClick={closeDrawer}>Create account</Link></>}<br/>Need help choosing parts?<br/><a href="#">Talk to an expert</a></div></div><CurrencySheet open={sheet} onClose={() => setSheet(false)} /></aside></div>}</>;
}
