"use client";

import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";

const assetPath = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH || ""}${path}`;
type Product = { name: string; image: string; price: string; old?: string; rating?: string; stock?: string; game?: boolean; meta?: string };
const hardware: Product[] = [
  { name: "ASUS TUF Gaming RTX 5070 Ti 16GB", image: "/images/placeholders/gpu-placeholder-01.jpg", price: "$799.99", old: "$849.99", rating: "4.8 (126)", stock: "In Stock" },
  { name: "AMD Ryzen 7 9800X3D Processor", image: "/images/placeholders/ram-placeholder-01.jpg", price: "$479.00", rating: "4.9 (88)", stock: "In Stock" },
  { name: "Samsung 990 PRO 2TB NVMe SSD", image: "/images/placeholders/ssd-placeholder-01.jpg", price: "$169.99", old: "$199.99", rating: "4.7 (203)", stock: "In Stock" },
  { name: "Corsair Vengeance 32GB DDR5 Memory", image: "/images/placeholders/ram-placeholder-01.jpg", price: "$114.99", rating: "4.8 (67)", stock: "In Stock" },
  { name: "MSI MAG 27in QHD 180Hz Monitor", image: "/images/placeholders/monitor-placeholder-01.jpg", price: "$249.99", old: "$289.99", rating: "4.6 (41)", stock: "In Stock" },
  { name: "Fractal Design North ATX Case", image: "/images/placeholders/gaming-pc-placeholder-01.jpg", price: "$149.99", rating: "4.7 (32)", stock: "In Stock" },
];
const games: Product[] = [
  { name: "Cyberpunk 2077", image: "/images/placeholders/game-placeholder-01.jpg", price: "$18.99", game: true, meta: "Steam · Global" },
  { name: "Elden Ring", image: "/images/placeholders/game-placeholder-02.jpg", price: "$29.99", game: true, meta: "Steam · Global" },
  { name: "Baldur's Gate 3", image: "/images/placeholders/game-placeholder-03.jpg", price: "$35.99", game: true, meta: "Steam · Global" },
  { name: "Black Myth: Wukong", image: "/images/placeholders/game-placeholder-04.jpg", price: "$42.49", game: true, meta: "Steam · Global" },
];
const categories = ["Graphics Cards", "Processors", "Motherboards", "Memory", "Storage", "Gaming PCs", "Gaming Laptops", "Monitors"];
const categoryImages = ["gpu-placeholder-01.jpg", "ram-placeholder-01.jpg", "gaming-pc-placeholder-01.jpg", "ram-placeholder-01.jpg", "ssd-placeholder-01.jpg", "gaming-pc-placeholder-01.jpg", "laptop-placeholder-01.jpg", "monitor-placeholder-01.jpg"];
const slides = [
  { eyebrow: "RTX 50 SERIES", title: "Upgrade your gaming PC.", text: "Next-generation graphics for play, create, and everything between.", action: "Shop GPUs", image: "/images/placeholders/hero-rtx-placeholder.png" },
  { eyebrow: "GAMING LAPTOP EVENT", title: "Performance goes anywhere.", text: "Save on RTX 5070 and 5080 gaming laptops this week.", action: "Shop laptops", image: "/images/placeholders/hero-laptop-placeholder.jpg" },
  { eyebrow: "PC BUILDER WEEK", title: "Build it your way.", text: "Start with compatible parts, finish with a PC you will love.", action: "Start building", image: "/images/placeholders/hero-builder-placeholder.jpg" },
  { eyebrow: "DIGITAL GAME DEALS", title: "More to play. Less to pay.", text: "Big PC and console games, delivered instantly.", action: "View game deals", image: "/images/placeholders/hero-games-placeholder.jpg" }
];
const drawerLevels: Record<string, string[]> = { root: ["Shop All", "PC Parts", "Computers", "Gaming", "Monitors", "Peripherals", "Storage", "Networking", "Digital Games", "Software", "PC Builder", "Brands", "Deals", "Clearance"], "PC Parts": ["Graphics Cards", "Processors", "Motherboards", "Memory", "Storage", "Power Supplies", "PC Cases", "Cooling", "Fans", "Accessories"], "Digital Games": ["PC Games", "Steam", "Xbox", "PlayStation", "Nintendo", "DLC", "Preorders", "New Releases", "Best Sellers", "On Sale", "Under $10", "Genres", "Publishers"] };
type QuickCategory = { name: string; icon: string; href: string };
const quickCategories: QuickCategory[] = [
  { name: "Steam", icon: "/images/placeholders/categories/steam.svg", href: "#" },
  { name: "Xbox", icon: "/images/placeholders/categories/xbox.svg", href: "#" },
  { name: "Sony", icon: "/images/placeholders/categories/sony.svg", href: "#" },
  { name: "eGift Card", icon: "/images/placeholders/categories/egift.svg", href: "#" },
  { name: "Nintendo", icon: "/images/placeholders/categories/nintendo.svg", href: "#" },
  { name: "Netflix", icon: "/images/placeholders/categories/netflix.svg", href: "#" },
  { name: "Apple", icon: "/images/placeholders/categories/apple.svg", href: "#" },
  { name: "Spotify", icon: "/images/placeholders/categories/spotify.svg", href: "#" },
];
type Promo = { name: string; eyebrow: string; title: string; text: string; action: string; desktopImage: string; mobileImage: string; wide?: boolean };
const promos: Promo[] = [
  { name: "component-week", eyebrow: "PC COMPONENT WEEK", title: "Save on the parts that power your build.", text: "Special pricing on GPUs, CPUs, and SSDs.", action: "Shop deals", desktopImage: "/images/placeholders/promos/promo-wide-placeholder.jpg", mobileImage: "/images/placeholders/promos/promo-wide-placeholder.jpg", wide: true },
  { name: "game-sale", eyebrow: "DIGITAL GAME DEALS", title: "15% off select PC games.", text: "Instant delivery. Ready when you are.", action: "Shop games", desktopImage: "/images/placeholders/promos/promo-left-placeholder.jpg", mobileImage: "/images/placeholders/promos/promo-left-placeholder.jpg" },
  { name: "sale-promotions", eyebrow: "CORECART SAVINGS", title: "Sales and promotions.", text: "Fresh offers across hardware and software.", action: "View all", desktopImage: "/images/placeholders/promos/promo-right-placeholder.jpg", mobileImage: "/images/placeholders/promos/promo-right-placeholder.jpg" },
];
function ProductCard({ item }: { item: Product }) { return <article className={`product ${item.game ? "game" : ""}`}><div className="product-image"><Image src={assetPath(item.image)} alt={item.name} fill sizes="(max-width: 640px) 50vw, (max-width: 1100px) 33vw, 17vw" /></div><div className="product-copy"><h3>{item.name}</h3>{item.game ? <p className="meta">{item.meta}</p> : <p className="rating">★★★★★ <span>{item.rating}</span></p>}<div className="price">{item.game && <small>From </small>}{item.price} {item.old && <del>{item.old}</del>}</div><div className="product-bottom">{item.game ? <span className="stock">Instant delivery</span> : <><span className="stock">{item.stock}</span><span className="shipping">Free shipping</span></>} </div>{!item.game && <button className="cart-button">Add to cart</button>}</div></article> }
function Section({ title, link, children }: { title: string; link?: string; children: React.ReactNode }) { return <section className="section"><div className="section-title"><h2>{title}</h2>{link && <a href="#">{link} <span aria-hidden="true">→</span></a>}</div>{children}</section> }
function QuickCategoryStrip() { const stripRef = useRef<HTMLDivElement>(null); const scroll = (distance: number) => stripRef.current?.scrollBy({ left: distance, behavior: "smooth" }); return <section className="quick-section" aria-label="Digital and service quick links"><div className="quick-nav"><button className="quick-arrow" aria-label="Scroll categories left" onClick={() => scroll(-280)}>←</button><div className="quick-track" ref={stripRef}>{quickCategories.map(category => <a className="quick-item" href={category.href} key={category.name}><Image src={assetPath(category.icon)} alt="" width={52} height={52}/><span>{category.name}</span></a>)}</div><button className="quick-arrow" aria-label="Scroll categories right" onClick={() => scroll(280)}>→</button></div></section> }
function PromoBanner({ promo }: { promo: Promo }) { return <a className={`promo-banner ${promo.wide ? "promo-wide" : ""}`} href="#"><div className="promo-image"><picture><source media="(max-width: 640px)" srcSet={assetPath(promo.mobileImage)}/><Image src={assetPath(promo.desktopImage)} alt="" fill sizes={promo.wide ? "(max-width: 640px) 100vw, 100vw" : "(max-width: 640px) 100vw, 50vw"}/></picture></div><div className="promo-copy"><p>{promo.eyebrow}</p><h3>{promo.title}</h3><span>{promo.text}</span><b>{promo.action} <span aria-hidden="true">→</span></b></div></a> }
function PromoBannerSection() { return <section className="promo-section" aria-labelledby="promo-heading"><div className="section-title"><h2 id="promo-heading">Featured promotions</h2><span className="quick-note">Limited-time offers</span></div><div className="promo-grid"><PromoBanner promo={promos[0]}/><PromoBanner promo={promos[1]}/><PromoBanner promo={promos[2]}/></div></section> }
export default function Storefront() {
  const [drawer, setDrawer] = useState(false); const [level, setLevel] = useState("root"); const [slide, setSlide] = useState(0); const [tab, setTab] = useState("Gaming Desktops"); const timer = useRef<ReturnType<typeof setInterval> | null>(null); const drawerRef = useRef<HTMLElement | null>(null);
  const closeDrawer = useCallback(() => { setDrawer(false); setLevel("root"); }, []);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "Escape") closeDrawer(); if (e.key === "ArrowRight") setSlide(s => (s + 1) % slides.length); if (e.key === "ArrowLeft") setSlide(s => (s + slides.length - 1) % slides.length); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [closeDrawer]);
  useEffect(() => { if (drawer) document.body.style.overflow = "hidden"; else document.body.style.overflow = ""; return () => { document.body.style.overflow = ""; }; }, [drawer]);
  useEffect(() => { if (drawer) drawerRef.current?.querySelector<HTMLButtonElement>("button")?.focus(); }, [drawer, level]);
  const startTimer = () => { if (!window.matchMedia("(prefers-reduced-motion: reduce)").matches && !timer.current) timer.current = setInterval(() => setSlide(s => (s + 1) % slides.length), 7000); }; const stopTimer = () => { if (timer.current) clearInterval(timer.current); timer.current = null; };
  useEffect(() => { startTimer(); return stopTimer; }, []);
  const trapFocus = (event: React.KeyboardEvent<HTMLElement>) => { if (event.key !== "Tab") return; const items = drawerRef.current?.querySelectorAll<HTMLElement>('button, a'); if (!items?.length) return; const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  return <><header><div className="topbar"><span>Free shipping on orders over $35</span><span>Help & support</span></div><div className="header-main"><button className="mobile-menu" aria-label="Open products menu" onClick={() => setDrawer(true)}>☰</button><a className="logo" href="#">core<span>cart</span></a><label className="search"><span>⌕</span><input aria-label="Search products" placeholder="Search PC parts, games, laptops, software..." /></label><button className="utility location"><b>⌖</b><span>Deliver to<br/><strong>Bangkok, Thailand</strong></span></button><button className="utility desktop-utility"><b>♙</b><span>Hello, sign in<br/><strong>Account</strong></span></button><button className="utility desktop-utility"><b>□</b><span>Returns<br/><strong>& Orders</strong></span></button><button className="cart" aria-label="Shopping cart"><b>🛒</b><span>Cart</span><i>2</i></button></div><div className="mobile-location">⌖ Deliver to <strong>Bangkok, Thailand</strong></div><nav><button onClick={() => setDrawer(true)}>☰ <strong>Products</strong></button>{["PC Parts", "Computers", "Gaming", "Digital Games", "Deals", "PC Builder", "Brands", "Clearance"].map(x => <a href="#" key={x}>{x}</a>)}</nav></header>
  {drawer && <div className="drawer-wrap" role="presentation"><button className="backdrop" aria-label="Close products menu" onClick={closeDrawer}/><aside ref={drawerRef} onKeyDown={trapFocus} className="drawer" aria-label="Product categories" role="dialog" aria-modal="true"><div className="drawer-top">{level !== "root" ? <button onClick={() => setLevel("root")}>← {level}</button> : <strong>Products</strong>}<button onClick={closeDrawer} aria-label="Close menu">×</button></div><ul>{drawerLevels[level].map(item => <li key={item}><button onClick={() => drawerLevels[item] ? setLevel(item) : closeDrawer()}>{item}{drawerLevels[item] && <span>›</span>}</button></li>)}</ul><div className="drawer-help">Need help choosing parts?<br/><a href="#">Talk to an expert</a></div></aside></div>}
  <main><section className="hero" onMouseEnter={stopTimer} onMouseLeave={startTimer}><div className="hero-image"><Image src={assetPath(slides[slide].image)} alt="" fill priority sizes="100vw" /></div><div className="hero-content"><p>{slides[slide].eyebrow}</p><h1>{slides[slide].title}</h1><span>{slides[slide].text}</span><button>{slides[slide].action} <b>→</b></button></div><div className="hero-controls"><button aria-label="Previous slide" onClick={() => setSlide(s => (s + slides.length - 1) % slides.length)}>←</button><div>{slides.map((_, i) => <button key={i} aria-label={`Show slide ${i + 1}`} aria-current={i === slide} className={i === slide ? "active" : ""} onClick={() => setSlide(i)} />)}</div><button aria-label="Next slide" onClick={() => setSlide(s => (s + 1) % slides.length)}>→</button></div></section>
  <QuickCategoryStrip />
  <Section title="Shop by category"><div className="categories">{categories.map((name, i) => <a href="#" key={name} className="category"><Image src={assetPath(`/images/placeholders/${categoryImages[i]}`)} alt="" fill sizes="(max-width: 640px) 40vw, 15vw"/><span>{name}</span></a>)}</div></Section>
  <PromoBannerSection />
  <Section title="Today's deals" link="See all deals"><div className="products">{hardware.slice(0, 5).map(x => <ProductCard item={x} key={x.name}/>)}</div></Section>
  <Section title="PC component deals" link="Shop components"><div className="products">{hardware.slice(1).map(x => <ProductCard item={x} key={x.name}/>)}</div></Section>
  <Section title="Digital game deals" link="View all games"><div className="products games">{games.map(x => <ProductCard item={x} key={x.name}/>)}</div></Section>
  <Section title="Gaming PCs & laptops"><div className="tabs" role="tablist">{["Gaming Desktops", "Gaming Laptops"].map(x => <button role="tab" aria-selected={tab === x} className={tab === x ? "selected" : ""} onClick={() => setTab(x)} key={x}>{x}</button>)}</div><div className="feature-row"><div><p>{tab === "Gaming Desktops" ? "READY TO SHIP" : "PORTABLE POWER"}</p><h3>{tab === "Gaming Desktops" ? "Built to run what you play." : "Play anywhere without compromise."}</h3><a href="#">Shop {tab.toLowerCase()} →</a></div><Image src={assetPath(tab === "Gaming Desktops" ? "/images/placeholders/hero-builder-placeholder.jpg" : "/images/placeholders/hero-laptop-placeholder.jpg")} alt="Gaming hardware" fill sizes="(max-width: 768px) 100vw, 50vw" /></div></Section>
  <Section title="Popular brands"><div className="brands">{["ASUS", "MSI", "AMD", "intel", "NVIDIA", "CORSAIR", "SAMSUNG"].map(x => <a href="#" key={x}>{x}</a>)}</div></Section>
  <Section title="Clearance & price drops" link="Shop clearance"><div className="products">{hardware.slice(0, 4).map(x => <ProductCard item={{...x, old: x.old || "$199.99"}} key={x.name}/>)}</div></Section>
  <Section title="Recently viewed"><div className="products recent">{hardware.slice(2, 5).map(x => <ProductCard item={x} key={x.name}/>)}</div></Section></main>
  <footer><div className="footer-inner"><a className="logo" href="#">core<span>cart</span></a><div><strong>Shop</strong><a href="#">PC parts</a><a href="#">Gaming</a><a href="#">Digital games</a></div><div><strong>Customer service</strong><a href="#">Order tracking</a><a href="#">Returns</a><a href="#">Contact us</a></div><div><strong>Stay in loop</strong><p>Deals, product launches, and build advice.</p><label className="email"><input placeholder="Email address"/><button>Join</button></label></div></div><p className="copyright">© 2026 CoreCart. Mock storefront, Phase 1.</p></footer></>;
}
